# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.Category', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c'),
        ),
    ]
