# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20170104_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isPublish', models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d?')),
                ('name', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('value', models.CharField(max_length=200, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0425\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0430 \u0442\u043e\u0432\u0430\u0440\u0430',
                'verbose_name_plural': '\u0425\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0438 \u0442\u043e\u0432\u0430\u0440\u0430(\u043e\u0432)',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['typePrefix', 'vendor', 'model'], 'verbose_name': '\u0422\u043e\u0432\u0430\u0440', 'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u044b'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='isPublish',
            field=models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d?'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(db_index=True, default=1, max_length=6, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='inStock',
            field=models.BooleanField(default=False, verbose_name='\u0412 \u043d\u0430\u043b\u0438\u0447\u0438\u0438?'),
        ),
        migrations.AddField(
            model_name='product',
            name='isPublish',
            field=models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d?'),
        ),
        migrations.AddField(
            model_name='product',
            name='mCode',
            field=models.CharField(default=1, max_length=8, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b \u041c\u0412\u0438\u0434\u0435\u043e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(db_index=True, default=1, max_length=200, verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='typePrefix',
            field=models.CharField(db_index=True, default=1, max_length=200, verbose_name='\u0422\u0438\u043f \u0442\u043e\u0432\u0430\u0440\u0430'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(db_index=True, default=1, max_length=200, verbose_name='\u041f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='\u0426\u0435\u043d\u0430'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
