# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20170106_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='params',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='params', to='store.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='mPrice',
            field=models.PositiveIntegerField(null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0432 \u041c\u0412\u0438\u0434\u0435\u043e'),
        ),
    ]
