# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='text',
            field=models.CharField(help_text='\u0412\u043c\u0435\u0441\u0442\u043e \u043f\u0435\u0440\u0435\u043c\u0435\u043d\u043d\u043e\u0439 \u0446\u0435\u043d\u044b \u041c\u0412\u0438\u0434\u0435\u043e \u0432\u043f\u0438\u0448\u0438 ## (\u0434\u0432\u0435 \u0440\u0435\u0448\u0435\u0442\u043a\u0438), \u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440, (## - 1000) * 0.95', max_length=200, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0444\u043e\u0440\u043c\u0443\u043b\u044b'),
        ),
    ]
