# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='formules',
            field=models.ManyToManyField(related_name='categories', to='store.Formula', verbose_name='\u0424\u043e\u0440\u043c\u0443\u043b\u044b'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/categories/%Y/%m/%d/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
    ]
