# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20170112_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='delivery_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438'),
            preserve_default=False,
        ),
    ]
