# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_category_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mUrl',
            field=models.URLField(default='', verbose_name='\u0421\u0441\u043b\u043a\u0430 \u043d\u0430 \u0441\u0430\u0439\u0442 \u041c\u0412\u0438\u0434\u0435\u043e'),
            preserve_default=False,
        ),
    ]
