# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-13 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_murl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(db_index=True, max_length=4, null=True, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mUrl',
            field=models.URLField(verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0441\u0430\u0439\u0442 \u041c\u0412\u0438\u0434\u0435\u043e'),
        ),
    ]
