# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20170108_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\xa1\xd0\xb0\xd0\xbc\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb2\xd0\xbe\xd0\xb7'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'\xd0\x90\xd0\xb4\xd1\x80\xd0\xb5\xd1\x81 \xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xb2\xd0\xba\xd0\xb8'),
        ),
    ]
